// ==========================================
// --- CENTRALIZED SUPABASE CONNECTION ---
// ==========================================
const SUPABASE_URL = 'https://wpqpqlwjprtwoblhvenw.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_89l1fu6nVSWxGVOH-g1dQw_i99aUXt9'; 

window.supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

window.handleSignOut = async function() {
    await window.supabaseClient.auth.signOut();
    window.location.href = 'index.html';
};

window.getSafeDate = function(dateString) {
    if (!dateString) return new Date();
    const parsed = new Date(dateString);
    return isNaN(parsed.getTime()) ? new Date() : parsed;
};

// ==========================================
// --- GLOBAL LANGUAGE TRANSLATION ENGINE ---
// ==========================================
const translations = {
    en: {
        "nav_dashboard": "Dashboard",
        "nav_events": "Events",
        "nav_guest_lists": "Guest Lists",
        "nav_gate_management": "Gate Management",
        "nav_create_manage": "Create & Manage",
        "nav_design_templates": "Design Templates",
        "nav_web_invites": "Web Invitations",
        "nav_analytics": "Analytics",
        "nav_reports": "Reports",
        "nav_my_profile": "My Profile",
        "nav_logout": "Logout",
        "nav_sub_create_event": "Create Event",
        "nav_sub_add_guest": "Add Guest",
        "sidebar_sec_events": "Events",
        "sidebar_sec_management": "Management",
        "sidebar_sec_design": "Design & Templates",
        "sidebar_sec_reports": "Reports",
        "header_logout": "Logout",
        "dash_welcome_main": "Welcome back,",
        "dash_welcome_sub": "Here's what's happening with your events.",
        "filter_all_time": "All Time",
        "filter_today": "Today",
        "filter_this_week": "This Week",
        "filter_this_month": "This Month",
        "filter_this_year": "This Year",
        "kpi_total_events": "Total Events",
        "kpi_total_guests": "Total Guests",
        "kpi_passes_issued": "Gate Passes Issued",
        "kpi_attendance_rate": "Attendance Rate",
        "qa_title": "Quick Actions",
        "qa_create_event": "Create Event",
        "qa_add_guests": "Add Guests",
        "qa_scan_qr": "Scan QR",
        "qa_reports": "Reports",
        "recent_events_title": "Recent Events",
        "recent_gates_title": "Recent Gate Passes",
        "view_all": "View All",
        "analytics_title": "Analytics Overview",
        "title_events": "Events",
        "sub_events": "Manage all your events",
        "search_events": "Search events by name, venue...",
        "title_guest_list": "Guest List",
        "sub_guest_list": "Manage and invite guests for your events",
        "search_guests": "Search guests by name, email or phone...",
        "title_gate_mgmt": "Gate Management",
        "sub_gate_mgmt": "Manage physical gates, assign staff, and monitor entry/exit logs",
        "search_gates": "Search gates or staff...",
        "title_create_manage": "Create & Manage",
        "sub_create_manage": "Dashboard > Create & Manage",
        "search_create_manage": "Search events, guests, gate passes...",
        "kpi_sub_all_time": "All Time",
        "kpi_sub_scheduled": "Scheduled",
        "kpi_sub_today": "Today",
        "kpi_sub_past": "Past Events",
        "kpi_sub_hidden": "Hidden",
        "kpi_upcoming": "Upcoming",
        "kpi_scheduled": "Scheduled",
        "kpi_ongoing": "Ongoing",
        "kpi_past_events": "Past Events",
        "kpi_completed": "Completed",
        "kpi_cancelled": "Cancelled",
        "kpi_hidden": "Hidden",
        "btn_create_event": "Create Event",
        "th_event_name": "Event Name",
        "th_date": "Date",
        "th_start_time": "Start Time",
        "th_venue": "Venue",
        "th_capacity": "Capacity",
        "th_approval": "Approval",
        "th_timeline": "Timeline",
        "th_actions": "Actions",
        "title_event_overview": "Event Overview",
        "title_recent_gates": "Recent Gates",
        "btn_view_all_gates": "View All Gates",
        "title_export_events": "Export Events",
        "desc_export_events": "Download your events data",
        "btn_export_excel": "Export to Excel",
        "label_select_event": "Select Event",
        "btn_add_guest": "Add Guest",
        "th_guest_name": "Guest Name",
        "th_contact": "Contact",
        "th_invitation_status": "Invitation Status",
        "th_sent_via": "Sent Via",
        "th_gate_pass": "Gate Pass",
        "th_exits": "Exits",
        "th_sent_on": "Sent On",
        "label_manage_gates_for": "Manage Gates For:",
        "btn_assign_gateman": "Assign Gateman",
        "btn_add_gate": "Add Gate",
        "kpi_total_gates": "Total Gates",
        "kpi_total_entries": "Total Entries",
        "kpi_total_exits": "Total Exits",
        "kpi_currently_inside": "Currently Inside",
        "kpi_qr_scanned": "QR Scanned",
        "title_gate_details": "Gate Details & Staff Operations",
        "th_gate_name": "Gate Name",
        "th_type": "Type",
        "th_assigned_staff": "Assigned Staff (PIN)",
        "th_status": "Status",
        "th_entries": "Entries",
        "th_inside": "Inside",
        "filter_all_events": "All Events",
        "filter_all_guests": "All Guests",
        "filter_all_gates": "All Gates",
        "form_event_info": "Event Information",
        "lbl_event_name": "Event Name",
        "plc_event_name": "Enter event name",
        "lbl_event_type": "Event Type",
        "plc_select_event_type": "Select event type",
        "lbl_event_date": "Event Date",
        "lbl_event_time": "Event Time",
        "lbl_to": "to",
        "lbl_venue": "Venue",
        "plc_venue": "Enter venue name",
        "lbl_address": "Address",
        "plc_address": "Enter full address",
        "lbl_organized_by": "Organized By",
        "plc_organized_by": "Enter organizer / company name",
        "lbl_contact_email": "Contact Email",
        "plc_email": "Enter email address",
        "lbl_contact_phone": "Contact Phone",
        "plc_phone": "Enter phone number",
        "lbl_description": "Description (Optional)",
        "plc_description": "Enter description",
        "form_capacity": "Capacity & Settings",
        "lbl_total_capacity": "Total Guests Capacity",
        "plc_capacity": "Enter total guest capacity",
        "desc_capacity": "This is the maximum number of guests allowed for this event.",
        "btn_cancel": "Cancel",
        "btn_submit_event": "Create Event →",
        "tips_title": "Tips",
        "tip_1": "Add a clear event name to help you identify it easily.",
        "tip_2": "Set the correct date and time for smooth guest management.",
        "tip_3": "You can update these details later if needed.",
        "tip_event_limit": "Event Limit:",
        "tip_guest_limit": "Guest Limit:",
        "msg_limit_events": "You can create up to",
        "msg_limit_guests": "Up to",
        "msg_guests_per_event": "guests per event.",
        "msg_events_word": "events.",
        "lbl_full_name": "Full Name",
        "plc_full_name": "Enter full name",
        "lbl_company": "Company / Organization",
        "plc_company": "Enter company name",
        "lbl_designation": "Designation / Title",
        "plc_designation": "Enter designation",
        "lbl_nationality": "Nationality",
        "plc_nationality": "Type or select nationality...",
        "lbl_id_type": "ID Type",
        "lbl_id_number": "ID Number",
        "plc_id_number": "Enter ID number",
        "lbl_ticket_type": "Ticket / Type",
        "lbl_pairs": "No. of Pairs / Capacity",
        "lbl_entry_gate": "Entry Gate",
        "lbl_exit_gate": "Exit Gate",
        "lbl_notes": "Notes (Optional)",
        "plc_notes": "Add any additional notes about this guest",
        "cm_card_create_title": "Create New Event",
        "cm_card_create_desc": "Create a new event and configure details.",
        "cm_card_add_title": "Add Guest",
        "cm_card_add_desc": "Add individual guest details manually.",
        "cm_card_import_title": "Import Data",
        "cm_card_import_desc": "Import events or guest data in bulk.",
        "btn_import_data_arrow": "Import Data →",
        "cm_your_events": "Your Events",
        "th_guests": "Guests",
        "btn_back_create_manage": "Back to Create & Manage",
        "ag_title": "Add Guest",
        "ag_subtitle": "Add individual guest details manually, or use bulk tools.",
        "ag_event_capacity": "Event Capacity",
        "ag_guests_added": "Guests Added",
        "ag_remaining_slots": "Remaining Slots",
        "ag_guests_in_event": "Guests in this Event",
        "btn_bulk_upload": "Bulk Upload (.xlsx)",
        "btn_auto_generate": "Auto-Generate",
        "ag_guest_info": "Guest Information",
        "bulk_title": "Upload Excel Guest List",
        "bulk_desc": "Requires columns: Guest Name, Ticket Tier, Capacity.",
        "btn_download_template": "Download Template",
        "btn_choose_file": "Choose Excel File",
        "txt_no_file": "No file chosen",
        "auto_title": "Auto-Generate Anonymous Passes",
        "auto_desc": "Generates batch passes named sequentially (e.g. VIP Pass - 001). Leave personal fields blank.",
        "lbl_number_passes": "Number of Passes *",
        "plc_number_passes": "e.g. 50",
        "btn_generate_passes": "Generate Passes",
        "inv_title": "Guest Invitation (Optional)",
        "inv_wa_title": "Send via WhatsApp",
        "inv_wa_desc": "Guest will receive invitation on WhatsApp",
        "inv_email_title": "Send via Email",
        "inv_email_desc": "Guest will receive invitation on Email",
        "btn_save_single_guest": "Save Single Guest",
        "dt_step1": "1. Choose a Template",
        "dt_filter_all": "All",
        "dt_filter_gen": "General",
        "dt_filter_mar": "Marriage",
        "dt_filter_corp": "Corporate",
        "dt_filter_vip": "VIP",
        "dt_step2": "2. Tools",
        "dt_add_text": "Add Text",
        "dt_image_lib": "Image Library",
        "dt_dynamic_tags": "Insert Dynamic Tags",
        "dt_tag_venue": "+ Venue",
        "dt_tag_date": "+ Date",
        "dt_tag_time": "+ Time",
        "dt_tag_tier": "+ Tier",
        "dt_text_format": "Text Formatting",
        "dt_line_space": "Line Space:",
        "dt_qr_props": "QR Properties",
        "dt_qr_size": "QR Size:",
        "dt_qr_color": "QR Color:",
        "dt_bg_box": "BG Box",
        "dt_box_radius": "Box Radius:",
        "dt_box_padding": "Box Padding:",
        "btn_delete_selected": "Delete Selected",
        "dt_step3": "3. Template Settings",
        "dt_tpl_name": "Template Name",
        "plc_tpl_name": "New Template Name",
        "dt_assign_event": "Assign to Event",
        "dt_preview_guest": "Preview with Guest",
        "btn_preview": "Preview",
        "btn_reset": "Reset",
        "btn_update_pass": "Update Pass",
        "btn_save_new": "Save as New",
        "dt_step4": "4. My Saved Templates",
        "wi_title": "Interactive Web Invitations",
        "wi_desc": "Build beautiful, scrolling RSVP websites for your events. Add music, galleries, and let guests register themselves instantly.",
        "wi_badge": "Coming Soon for Premium Tenants",
        "prof_title": "My Profile",
        "prof_plan_limits": "Plan & Limits",
        "prof_plan_desc": "Here is an overview of your current subscription benefits.",
        "prof_max_events": "Max Events",
        "prof_max_guests": "Max Guests / Event",
        "prof_active_feats": "Active Features",
        "btn_view_upgrade": "View Upgrade Options",
        "btn_save_changes": "Save Changes",
        "upg_feat_1": "Increase Event & Guest Limits",
        "upg_feat_2": "Custom Brand Fonts & AI Tools",
        "upg_feat_3": "Bulk Excel Guest Uploads",
        "upg_footer": "Downgrades will not keep higher plan features.",
        "upg_btn_down_basic": "Downgrade to Basic",
        "upg_btn_up_pro": "Upgrade to Pro",
        "upg_btn_down_pro": "Downgrade to Pro",
        "upg_btn_up_prem": "Upgrade to Premium",
        "upg_title_change": "Change",
        "upg_title_plan": "Subscription Plan",
        "upg_desc_curr_plan": "You are currently on the",
        "upg_desc_curr_plan_2": "plan. Select a new plan below to request a change.",
        "upg_desc_feat_1": "The feature",
        "upg_desc_feat_2": "requires a different plan. Select an option below to request an account update.",
        "warn_event_limit": "⚠️ LIMIT REACHED: Your plan allows a maximum of",
        "warn_event_limit_2": "events. You must upgrade to create more.",
        "warn_guest_limit": "⚠️ LIMIT REACHED: This event has hit your plan limit of",
        "warn_guest_limit_2": "guests. You cannot add more."
    },
    ar: {
        "nav_dashboard": "لوحة القيادة",
        "nav_events": "الفعاليات",
        "nav_guest_lists": "قوائم الضيوف",
        "nav_gate_management": "إدارة البوابات",
        "nav_create_manage": "إنشاء وإدارة",
        "nav_design_templates": "قوالب التصميم",
        "nav_web_invites": "دعوات الويب",
        "nav_analytics": "التحليلات",
        "nav_reports": "التقارير",
        "nav_my_profile": "ملفي الشخصي",
        "nav_logout": "تسجيل خروج",
        "nav_sub_create_event": "إنشاء فعالية",
        "nav_sub_add_guest": "إضافة ضيف",
        "sidebar_sec_events": "الفعاليات",
        "sidebar_sec_management": "الإدارة",
        "sidebar_sec_design": "التصميم والقوالب",
        "sidebar_sec_reports": "التقارير",
        "header_logout": "تسجيل خروج",
        "dash_welcome_main": "مرحباً بعودتك،",
        "dash_welcome_sub": "إليك ما يحدث مع فعالياتك.",
        "filter_all_time": "كل الوقت",
        "filter_today": "اليوم",
        "filter_this_week": "هذا الأسبوع",
        "filter_this_month": "هذا الشهر",
        "filter_this_year": "هذا العام",
        "kpi_total_events": "إجمالي الفعاليات",
        "kpi_total_guests": "إجمالي الضيوف",
        "kpi_passes_issued": "تصاريح الدخول المصدرة",
        "kpi_attendance_rate": "معدل الحضور",
        "qa_title": "إجراءات سريعة",
        "qa_create_event": "إنشاء فعالية",
        "qa_add_guests": "إضافة ضيوف",
        "qa_scan_qr": "مسح QR",
        "qa_reports": "التقارير",
        "recent_events_title": "الفعاليات الأخيرة",
        "recent_gates_title": "تصاريح الدخول الأخيرة",
        "view_all": "عرض الكل",
        "analytics_title": "نظرة عامة على التحليلات",
        "title_events": "الفعاليات",
        "sub_events": "إدارة جميع فعالياتك",
        "search_events": "البحث عن الفعاليات بالاسم، الموقع...",
        "title_guest_list": "قائمة الضيوف",
        "sub_guest_list": "إدارة ودعوة الضيوف لفعالياتك",
        "search_guests": "البحث عن الضيوف بالاسم، البريد أو الهاتف...",
        "title_gate_mgmt": "إدارة البوابات",
        "sub_gate_mgmt": "إدارة البوابات الفعلية، تعيين الموظفين، ومراقبة سجلات الدخول/الخروج",
        "search_gates": "البحث عن البوابات أو الموظفين...",
        "title_create_manage": "إنشاء وإدارة",
        "sub_create_manage": "لوحة القيادة > إنشاء وإدارة",
        "search_create_manage": "البحث عن الفعاليات، الضيوف، تصاريح الدخول...",
        "kpi_sub_all_time": "كل الوقت",
        "kpi_sub_scheduled": "مجدولة",
        "kpi_sub_today": "اليوم",
        "kpi_sub_past": "فعاليات سابقة",
        "kpi_sub_hidden": "مخفية",
        "kpi_upcoming": "القادمة",
        "kpi_scheduled": "مجدولة",
        "kpi_ongoing": "جارية",
        "kpi_past_events": "فعاليات سابقة",
        "kpi_completed": "مكتملة",
        "kpi_cancelled": "ملغاة",
        "kpi_hidden": "مخفية",
        "btn_create_event": "إنشاء فعالية",
        "th_event_name": "اسم الفعالية",
        "th_date": "التاريخ",
        "th_start_time": "وقت البدء",
        "th_venue": "الموقع",
        "th_capacity": "السعة",
        "th_approval": "الموافقة",
        "th_timeline": "الجدول الزمني",
        "th_actions": "الإجراءات",
        "title_event_overview": "نظرة عامة على الفعالية",
        "title_recent_gates": "البوابات الأخيرة",
        "btn_view_all_gates": "عرض جميع البوابات",
        "title_export_events": "تصدير الفعاليات",
        "desc_export_events": "تحميل بيانات فعالياتك",
        "btn_export_excel": "تصدير إلى Excel",
        "label_select_event": "اختر الفعالية",
        "btn_add_guest": "إضافة ضيف",
        "th_guest_name": "اسم الضيف",
        "th_contact": "جهة الاتصال",
        "th_invitation_status": "حالة الدعوة",
        "th_sent_via": "أُرسلت عبر",
        "th_gate_pass": "تصريح الدخول",
        "th_exits": "الخروج",
        "th_sent_on": "تاريخ الإرسال",
        "label_manage_gates_for": "إدارة بوابات:",
        "btn_assign_gateman": "تعيين حارس",
        "btn_add_gate": "إضافة بوابة",
        "kpi_total_gates": "إجمالي البوابات",
        "kpi_total_entries": "إجمالي الدخول",
        "kpi_total_exits": "إجمالي الخروج",
        "kpi_currently_inside": "بالداخل حالياً",
        "kpi_qr_scanned": "مسح QR",
        "title_gate_details": "تفاصيل البوابات والموظفين",
        "th_gate_name": "اسم البوابة",
        "th_type": "النوع",
        "th_assigned_staff": "الموظف المعين (الرمز)",
        "th_status": "الحالة",
        "th_entries": "الدخول",
        "th_inside": "بالداخل",
        "filter_all_events": "كل الفعاليات",
        "filter_all_guests": "كل الضيوف",
        "filter_all_gates": "كل البوابات",
        "form_event_info": "معلومات الفعالية",
        "lbl_event_name": "اسم الفعالية",
        "plc_event_name": "أدخل اسم الفعالية",
        "lbl_event_type": "نوع الفعالية",
        "plc_select_event_type": "اختر نوع الفعالية",
        "lbl_event_date": "تاريخ الفعالية",
        "lbl_event_time": "وقت الفعالية",
        "lbl_to": "إلى",
        "lbl_venue": "الموقع",
        "plc_venue": "أدخل اسم الموقع",
        "lbl_address": "العنوان",
        "plc_address": "أدخل العنوان بالكامل",
        "lbl_organized_by": "تنظيم بواسطة",
        "plc_organized_by": "أدخل اسم المنظم / الشركة",
        "lbl_contact_email": "البريد الإلكتروني",
        "plc_email": "أدخل البريد الإلكتروني",
        "lbl_contact_phone": "رقم الهاتف",
        "plc_phone": "أدخل رقم الهاتف",
        "lbl_description": "الوصف (اختياري)",
        "plc_description": "أدخل الوصف",
        "form_capacity": "السعة والإعدادات",
        "lbl_total_capacity": "إجمالي سعة الضيوف",
        "plc_capacity": "أدخل إجمالي سعة الضيوف",
        "desc_capacity": "هذا هو الحد الأقصى لعدد الضيوف المسموح به لهذه الفعالية.",
        "btn_cancel": "إلغاء",
        "btn_submit_event": "إنشاء الفعالية ←",
        "tips_title": "نصائح",
        "tip_1": "أضف اسمًا واضحًا للفعالية لمساعدتك في التعرف عليها بسهولة.",
        "tip_2": "حدد التاريخ والوقت الصحيحين لإدارة الضيوف بسلاسة.",
        "tip_3": "يمكنك تحديث هذه التفاصيل لاحقًا إذا لزم الأمر.",
        "tip_event_limit": "حد الفعاليات:",
        "tip_guest_limit": "حد الضيوف:",
        "msg_limit_events": "يمكنك إنشاء حتى",
        "msg_limit_guests": "حتى",
        "msg_guests_per_event": "ضيف لكل فعالية.",
        "msg_events_word": "فعاليات.",
        "lbl_full_name": "الاسم الكامل",
        "plc_full_name": "أدخل الاسم الكامل",
        "lbl_company": "الشركة / المؤسسة",
        "plc_company": "أدخل اسم الشركة",
        "lbl_designation": "المسمى الوظيفي",
        "plc_designation": "أدخل المسمى الوظيفي",
        "lbl_nationality": "الجنسية",
        "plc_nationality": "اكتب أو اختر الجنسية...",
        "lbl_id_type": "نوع الهوية",
        "lbl_id_number": "رقم الهوية",
        "plc_id_number": "أدخل رقم الهوية",
        "lbl_ticket_type": "التذكرة / النوع",
        "lbl_pairs": "عدد المرافقين / السعة",
        "lbl_entry_gate": "بوابة الدخول",
        "lbl_exit_gate": "بوابة الخروج",
        "lbl_notes": "ملاحظات (اختياري)",
        "plc_notes": "أضف أي ملاحظات إضافية حول هذا الضيف",
        "cm_card_create_title": "إنشاء فعالية جديدة",
        "cm_card_create_desc": "إنشاء فعالية جديدة وتكوين التفاصيل.",
        "cm_card_add_title": "إضافة ضيف",
        "cm_card_add_desc": "إضافة تفاصيل الضيف الفردية يدويًا.",
        "cm_card_import_title": "استيراد البيانات",
        "cm_card_import_desc": "استيراد الفعاليات أو بيانات الضيوف دفعة واحدة.",
        "btn_import_data_arrow": "استيراد البيانات ←",
        "cm_your_events": "فعالياتك",
        "th_guests": "الضيوف",
        "btn_back_create_manage": "العودة إلى الإدارة",
        "ag_title": "إضافة ضيف",
        "ag_subtitle": "أضف تفاصيل الضيف يدويًا، أو استخدم أدوات الاستيراد الشامل.",
        "ag_event_capacity": "سعة الفعالية",
        "ag_guests_added": "الضيوف المضافين",
        "ag_remaining_slots": "الأماكن المتبقية",
        "ag_guests_in_event": "الضيوف في هذه الفعالية",
        "btn_bulk_upload": "رفع ملف (.xlsx)",
        "btn_auto_generate": "توليد تلقائي",
        "ag_guest_info": "معلومات الضيف",
        "bulk_title": "رفع قائمة ضيوف Excel",
        "bulk_desc": "يتطلب أعمدة: اسم الضيف، نوع التذكرة، السعة.",
        "btn_download_template": "تحميل القالب",
        "btn_choose_file": "اختيار ملف Excel",
        "txt_no_file": "لم يتم اختيار ملف",
        "auto_title": "توليد تصاريح مجهولة تلقائياً",
        "auto_desc": "يولد تصاريح بأسماء متسلسلة (مثال VIP Pass - 001). اترك الحقول الشخصية فارغة.",
        "lbl_number_passes": "عدد التصاريح *",
        "plc_number_passes": "مثال 50",
        "btn_generate_passes": "توليد التصاريح",
        "inv_title": "دعوة الضيف (اختياري)",
        "inv_wa_title": "إرسال عبر واتساب",
        "inv_wa_desc": "سيتلقى الضيف الدعوة عبر واتساب",
        "inv_email_title": "إرسال عبر الإيميل",
        "inv_email_desc": "سيتلقى الضيف الدعوة عبر الإيميل",
        "btn_save_single_guest": "حفظ ضيف واحد",
        "dt_step1": "1. اختر قالباً",
        "dt_filter_all": "الكل",
        "dt_filter_gen": "عام",
        "dt_filter_mar": "زواج",
        "dt_filter_corp": "شركات",
        "dt_filter_vip": "VIP",
        "dt_step2": "2. الأدوات",
        "dt_add_text": "إضافة نص",
        "dt_image_lib": "مكتبة الصور",
        "dt_dynamic_tags": "إدراج علامات ديناميكية",
        "dt_tag_venue": "+ الموقع",
        "dt_tag_date": "+ التاريخ",
        "dt_tag_time": "+ الوقت",
        "dt_tag_tier": "+ النوع",
        "dt_text_format": "تنسيق النص",
        "dt_line_space": "تباعد الأسطر:",
        "dt_qr_props": "خصائص QR",
        "dt_qr_size": "حجم QR:",
        "dt_qr_color": "لون QR:",
        "dt_bg_box": "خلفية",
        "dt_box_radius": "انحناء الزوايا:",
        "dt_box_padding": "حجم الإطار:",
        "btn_delete_selected": "حذف المحدد",
        "dt_step3": "3. إعدادات القالب",
        "dt_tpl_name": "اسم القالب",
        "plc_tpl_name": "اسم القالب الجديد",
        "dt_assign_event": "تعيين لفعالية",
        "dt_preview_guest": "معاينة مع ضيف",
        "btn_preview": "معاينة",
        "btn_reset": "إعادة ضبط",
        "btn_update_pass": "تحديث التصريح",
        "btn_save_new": "حفظ كجديد",
        "dt_step4": "4. قوالبي المحفوظة",
        "wi_title": "دعوات الويب التفاعلية",
        "wi_desc": "قم ببناء مواقع RSVP بتمرير جميل لفعالياتك. أضف الموسيقى والمعارض ودع الضيوف يسجلون أنفسهم على الفور.",
        "wi_badge": "قريباً للمشتركين المميزين",
        "prof_title": "ملفي الشخصي",
        "prof_plan_limits": "الخطة والحدود",
        "prof_plan_desc": "إليك نظرة عامة على مزايا اشتراكك الحالي.",
        "prof_max_events": "الحد الأقصى للفعاليات",
        "prof_max_guests": "الحد الأقصى للضيوف / الفعالية",
        "prof_active_feats": "الميزات النشطة",
        "btn_view_upgrade": "عرض خيارات الترقية",
        "btn_save_changes": "حفظ التغييرات",
        "upg_feat_1": "زيادة حدود الفعاليات والضيوف",
        "upg_feat_2": "خطوط مخصصة وأدوات ذكاء اصطناعي",
        "upg_feat_3": "رفع ملفات Excel للضيوف",
        "upg_footer": "لن تحتفظ الباقات الأقل بميزات الباقات الأعلى.",
        "upg_btn_down_basic": "تخفيض إلى الأساسية (Basic)",
        "upg_btn_up_pro": "ترقية إلى المتقدمة (Pro)",
        "upg_btn_down_pro": "تخفيض إلى المتقدمة (Pro)",
        "upg_btn_up_prem": "ترقية إلى المميزة (Premium)",
        "upg_title_change": "تغيير",
        "upg_title_plan": "خطة الاشتراك",
        "upg_desc_curr_plan": "أنت حالياً على خطة",
        "upg_desc_curr_plan_2": ". اختر خطة جديدة أدناه لطلب التغيير.",
        "upg_desc_feat_1": "الميزة",
        "upg_desc_feat_2": "تتطلب خطة مختلفة. اختر خياراً أدناه لطلب تحديث الحساب.",
        "warn_event_limit": "⚠️ تم الوصول للحد الأقصى: خطتك تسمح بحد أقصى",
        "warn_event_limit_2": "فعاليات. يجب عليك الترقية لإنشاء المزيد.",
        "warn_guest_limit": "⚠️ تم الوصول للحد الأقصى: وصلت هذه الفعالية إلى حد خطتك وهو",
        "warn_guest_limit_2": "ضيوف. لا يمكنك إضافة المزيد."
    }
};

window.t = function(key, fallbackText) {
    let currentLanguage = localStorage.getItem('qrg_lang') || 'en';
    if (translations[currentLanguage] && translations[currentLanguage][key]) {
        return translations[currentLanguage][key];
    }
    return fallbackText;
};

window.toggleLanguage = function() {
    let currentLanguage = localStorage.getItem('qrg_lang') || 'en';
    currentLanguage = currentLanguage === 'en' ? 'ar' : 'en';
    localStorage.setItem('qrg_lang', currentLanguage);
    window.applyLanguage();
};

window.applyLanguage = function() {
    let currentLanguage = localStorage.getItem('qrg_lang') || 'en';
    const isArabic = currentLanguage === 'ar';
    
    document.documentElement.dir = isArabic ? 'rtl' : 'ltr';
    document.documentElement.lang = currentLanguage;

    const langBtn = document.getElementById('btnLangToggle');
    if (langBtn) {
        langBtn.innerText = isArabic ? 'English' : 'عربي';
    }

    const sidebar = document.getElementById('mainSidebar');
    if (sidebar) {
        if (isArabic) {
            sidebar.style.borderRight = 'none';
            sidebar.style.borderLeft = '1px solid var(--color-border)';
        } else {
            sidebar.style.borderLeft = 'none';
            sidebar.style.borderRight = '1px solid var(--color-border)';
        }
    }

    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[currentLanguage] && translations[currentLanguage][key]) {
            if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                element.placeholder = translations[currentLanguage][key];
            } else {
                element.innerText = translations[currentLanguage][key];
            }
        }
    });
};

document.addEventListener('DOMContentLoaded', () => {
    window.applyLanguage();
});
